### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by andrewharvey** [beyondtracks/beyondtracks#1]
# High Level New Features
- [ ] better support for multi day walks
- [ ] beyondtracks.co.nz for NZ walks
- [ ] beyondtracks.com.au for AU walks
- [ ] time from home #2
- [ ] allow users to search for walks within the country, but lists should default to walks accessible within a day
- [ ] offline application (should precache all walks and and maps) **premium feature**
- [ ] subscribe to per walk updates (email or sms) (any changes to the walk, bushfires or park alert changes) **premium feature**
- [x] autogenerated walk description for html/og description. Should this show up on the page?
- [ ] remoteness measure (inverse of [1km population grid](http://www.abs.gov.au/AUSSTATS/abs@.nsf/Lookup/1270.0.55.007Main+Features12011?OpenDocument))
- [ ] 3D maps
- [ ] Mapillary integration

# Refactoring
- [x] port to Vue.js/Nuxtjs
* aims to
   * improve initial load of /
   * cleaner code base
   * still use server side rendering
- [x] use new Mapbox GL JS map (https://www.beyondtracks.com/map)
- [ ] fix broken comments
- [x] fix uneven elevation graph for return walks
- [ ] clean up walk page design
- [ ] walk tags
- [ ] limit park labels in map based on area per zoom
- [ ] cluster walk icons on map
- [ ] walk card/3rd party embed api **enterprise feature**
