### ISSUE TITLE
new walks

### ISSUE THREAD

**Issue by andrewharvey** [beyondtracks/beyondtracks#4]
- [ ] The Basin https://www.beyondtracks.com/map/#15.13/-33.1071/151.2332 [missing in OSM]
- [ ] Crafts Wall https://www.beyondtracks.com/map/#15.14/-33.9793/150.1417 (shorter walk than Cloudmaker)
- [ ] T3 Track https://www.beyondtracks.com/map/#14.82/-33.398/150.6574
- [ ] Barrington https://www.beyondtracks.com/map/#16.94/-32.10981/151.47783
- [ ] The Big Hole https://www.beyondtracks.com/map/#17.02/-32.0324/151.47069
- [ ] The Rock https://www.beyondtracks.com/map/#14.68/-35.2684/147.0787
- [ ] Jacks Creek https://www.beyondtracks.com/map/#16.58/-34.13293/146.20357
- [ ] Mount Coryah https://www.beyondtracks.com/map/#16.01/-30.28132/150.1271
- [ ] Mount Yulludunida https://www.beyondtracks.com/map/#14.95/-30.2854/150.0832
- [ ] Mount Cougal https://www.beyondtracks.com/map/#14.48/-28.243/153.344
- [ ] https://www.beyondtracks.com/map/#14.48/-28.2133/153.2883
- [ ] https://www.beyondtracks.com/map/#14.78/-29.2427/153.3792
- [ ] https://www.beyondtracks.com/map/#14.22/-29.5449/152.3144
- [ ] https://www.beyondtracks.com/map/#15.15/-29.4728/152.3311
- [ ] Never Never https://www.beyondtracks.com/map/#14.29/-30.3633/152.7994
- [ ] Dorrigo https://www.beyondtracks.com/map/#14.84/-30.3727/152.7339
- [ ] Point Lookout https://www.beyondtracks.com/map/#14.18/-30.5022/152.4168
- [ ] https://www.beyondtracks.com/map/#14.41/-30.3988/152.2622
- [ ] Wollomombi https://www.beyondtracks.com/map/#14.82/-30.5379/152.0393
- [ ] https://www.beyondtracks.com/map/#15.1/-31.0547/153.0647
- [ ] South West Rocks https://www.beyondtracks.com/map/#13.34/-30.9065/153.0832
- [ ] https://www.beyondtracks.com/map/#13.26/-35.2747/150.0813
- [ ] Twinderry Twin Peak https://www.beyondtracks.com/map/#14.21/-35.6711/149.2518
- [ ] https://www.beyondtracks.com/map/#15.14/-35.5622/148.9928
- [ ] Mount Wee Jasper https://www.beyondtracks.com/map/#13.77/-35.1475/148.6488
- [ ] https://www.beyondtracks.com/map/#13.66/-35.6277/148.3536
- [ ] https://www.beyondtracks.com/map/#17.34/-35.64022/148.24932
- [ ] Watagan https://www.beyondtracks.com/map/#13.02/-32.9982/151.4358
- [ ] Rocky Crossing Track https://www.beyondtracks.com/map/#14.34/-32.1427/151.5203
- [ ] https://www.beyondtracks.com/map/#14.67/-30.6804/151.746
- [ ] https://www.beyondtracks.com/map/#14.21/-30.4308/152.2521
- [ ] Mount Kaputar https://www.beyondtracks.com/map/#14.2/-30.2852/150.1648
- [ ] https://www.beyondtracks.com/map/#13.75/-37.3615/149.9557
- [ ] Killalea State Park

Edits:

 - [ ] https://www.beyondtracks.com/walks/-/bass-point-coastal-loop/ full loop around the headland

Canyons? Should they be included?
- [ ] Wollangambe River

**Comment by andrewharvey** [comment]
issue moved to https://gitlab.com/beyondtracks/beyondtracks-walks/issues/2
